[package]
name = "chartcharm_database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Rustqlite from github
# https://github.com/kawasin73/prsqlite/
prsqlite = { git = "https://github.com/kawasin73/prsqlite/", rev = "3d6cbb"}
dirs = "5"
async-std = { version = "1", features = ["attributes"] }
