name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y webkit2gtk-4.0 build-essential libwebkit2gtk-4.0-dev gcc

      - name: Install Dependencies
        run: |
          cargo install --locked tauri-cli
          rustup target add wasm32-unknown-unknown
          cargo install --locked trunk
          cargo install --locked wasm-bindgen-cli

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install esbuild
        run: npm install --global --save-exact esbuild

      - name: Build
        run: cargo tauri build --verbose

      - name: Clippy
        run: cargo clippy --verbose --all -- -W clippy::all -W clippy::pedantic -W clippy::nursery -D warnings -A clippy::module_name_repetitions
